# Generated by Django 5.2.17 on 2026-10-04 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("city_code", models.IntegerField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["city_name"],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["interest_name"],
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                ("postal_code", models.IntegerField(primary_key=True, serialize=False)),
                ("area_name", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhoods",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ["area_name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notif_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("url", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="notif_recipient_read_idx"
                    )
                ],
            },
        ),
    ]